version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'docker'
    directory: '/packages/deep-heating'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'docker'
    directory: '/packages/deep-heating-socketio'
    schedule:
      interval: 'daily'
