name: Setup
description: Set up Nix environment with caching for CI workflows

inputs:
  github-token:
    description: 'GitHub token for Nix installer and cache API'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@2c9db80fb984ceb1bcaa77cdda3fdf8cfba92035 # v34
      with:
        github_access_token: ${{ inputs.github-token }}
        nix_conf: |
          experimental-features = nix-command flakes
          accept-flake-config = true

    - name: Cache Nix store
      uses: nix-community/cache-nix-action@135667ec418502fa5a3598af6fb9eb733888ce6a # v6
      with:
        primary-key: nix-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('flake.lock') }}
        restore-prefixes-first-match: |
          nix-${{ runner.os }}-${{ runner.arch }}-
        gc-max-store-size-linux: 2G
        gc-max-store-size-macos: 2G
