#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

LIST=$(git diff-index --diff-filter=d --name-only --cached HEAD)
if [ "$LIST" ]; then
  bunx prettier --ignore-unknown --write $LIST
  git add $LIST
fi
